
baseURL= "https://osacon.io"
canonifyURLs = false
title = "The Open Source Analytics Conference"
description = "The Open Source Analytics Conference (OSA CON) is the go-to conference for all things open-source analytics."
enableRobotsTXT = true
RemovePathAccents = true
DefaultContentLanguage = "en"

theme = "osacon"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"


############################## navigation ###############################
[menu]

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Sessions"
  url = "/sessions/2023"
  weight = 2

[[menu.main]]
  name = "Speakers"
  url = "/speakers"
  weight = 3

[[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7


# Everything below this are Site Params

[params]
description = "The Open Source Analytics Conference (OSA CON) is the go-to conference for all things open-source analytics."
logo = "/images/osacon2024-logo-h.png"
home = "Home"
privacy_policy = "/privacy"
google_analytics = "G-GLFP2KJWR4"

# First one is picked as the Twitter card image if not set on page.
images = ["/images/osacon2024-card.jpg"]
start_date = "2023-12-12T09:00-05:00"
end_date = "2023-12-14T17:00-05:00" 

[params.hero]
text = "November 19-21, 2024. Online event."

[params.hero.cta1]
text = "Become a speaker"
link = "http://sessionize.com/osa-con-2024"

# Navigation button
[params.navigation_button]
enable = true
label = "Call for presentations"
link = "https://sessionize.com/osa-con-2024/"


[params.links]
[[params.links.social]]
    name = "Email us"
    url = "mailto:hello@osacon.io"
    icon = "fa fa-envelope"

[[params.links.footer_resources]]
    name = "Code of Conduct"
    url = "/coc"

# [[params.links.footer_resources]]
#    name = "Prospectus"
#    url = "/files/OSACON2023-Prospectus_v1_2.pdf"

[[params.links.footer_resources]] 
    name = "Privacy Policy"
    url = "/privacy"

[[params.links.footer_previous]]
    name = "OSA CON 2023"
    url = "/sessions/2023"
[[params.links.footer_previous]]
    name = "OSA CON 2022"
    url = "https://altinity.com/osa-con2022/"
[[params.links.footer_previous]]
    name = "OSA CON 2021"
    url = "https://altinity.com/osa-con-2021/"


[permalinks]
tags = "/blog/tags/:slug/"
posts = "/:year/:month/:title/"

############################# Plugins ##############################




# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap.min.css"

[[params.plugins.css]]
link = "/plugins/bootstrap-table.min.css"

[[params.plugins.css]]
link = "/plugins/fontawesome.css"

[[params.plugins.css]]
link = "/plugins/swiper-bundle.min.css"

# JS Plugins
[[params.plugins.js]]
link="/plugins/jquery.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap-table.min.js"

[[params.plugins.js]]
link="/plugins/swiper-bundle.min.js"
